webapp/checkout.jsp
webapp/contact.jsp
webapp/css/style.css
webapp/index.jsp
webapp/js/signup.js
webapp/main.jsp
webapp/shop-details.jsp
webapp/shop-grid.jsp
webapp/shoping-cart.jsp
webapp/signin.jsp
webapp/signup.jsp

💛 [FEAT] 로그인 페이지 목업

---

src/app/dto/Author.java
src/app/dto/Cart.java
src/app/dto/Category.java
src/app/dto/Member.java
src/app/dto/Order.java
src/app/dto/OrderDetail.java
src/app/dto/Product.java
src/app/dto/Publisher.java
src/app/dto/Review.java
src/web/controller/CustServlet.java

✈ [FEAT] DTO Lombok annotation 추가

---

webapp/signup.jsp

🎈 [FIX] JSP 태그 오류 해결

---

webapp/checkout.jsp
webapp/index.jsp

🎈 [INIT] 프로젝트 초기 설정

---

resources/mapper/OrderMapper.xml
src/app/dto/Order.java
src/app/impl/order/OrderServiceImpl.java
src/app/order/OrderDaoImpl.java
src/app/order/OrderServiceImpl.java
test/order/OrderInsert.java
test/order/OrderSelect.java

💛 [FEAT] OrderMapper, OrderTest 구현

---

resources/mapper/ProductMapper.xml

😀[Merge]: Merged master into jinwoo branch

---

src/app/impl/product/ProductDaoImpl.java
src/app/impl/product/ProductServiceImpl.java
src/web/controller/MainServlet.java
test/product/ProductSelect.java
webapp/checkoutbuynow.jsp
webapp/index.jsp
webapp/shop-details.jsp

💛 [FEAT] 바로 주문 구현

---

resources/mapper/CartMapper.xml
resources/mybatis.xml
resources/mysql.properties
src/app/dto/response/CartProduct.java
src/app/impl/cart/CartDaoImpl.java
src/app/impl/cart/CartServiceImpl.java
src/web/controller/MainServlet.java
src/web/controller/MemberServlet.java
test/cart/CartTest.java
webapp/main.jsp
webapp/mypage.jsp

🎈 [FEAT] 내 장바구니 목록 전체 조회

---

resources/mysql.properties
src/web/controller/MemberServlet.java

🎈 [FIX] mysql.properties 변경 취소

---

resources/mapper/OrderDetailMapper.xml
resources/mapper/OrderMapper.xml
resources/mybatis.xml
src/app/dto/entity/Order.java
src/app/dto/entity/OrderDetail.java
src/app/impl/order/OrderDaoImpl.java
src/app/impl/order/OrderServiceImpl.java
src/app/impl/orderdetail/OrderDetailDaoImpl.java
src/app/impl/orderdetail/OrderDetailServiceImpl.java
src/web/controller/MainServlet.java
webapp/mypage.jsp

- 마이페이지에서 주문 내역 (ORDER + ORDERDETAIL + PRODUCT) 연동

💛 [FEAT] MY PAGE 주문 내역 API 연동

---

webapp/signin.jsp

😀[HOTFIX]:로그인 페이지 alert오류 수정

---

src/web/controller/MainServlet.java

🎈 [FIX] 충돌 해결

---

resources/mapper/CartMapper.xml
src/app/dto/response/CartProduct.java
src/app/impl/cart/CartDaoImpl.java
src/app/impl/cart/CartServiceImpl.java
src/web/controller/MainServlet.java
webapp/404.jsp
webapp/checkout-result.jsp
webapp/checkout.jsp
webapp/checkoutbuynow.jsp
webapp/contact.jsp
webapp/mypage.jsp
webapp/shop-details.jsp
webapp/shop-grid.jsp
webapp/shoping-cart.jsp
webapp/signin.jsp
webapp/signup.jsp

🎈 [FEAT] 장바구니 선택된 상품 결제 내역으로 보내기

---

webapp/checkout.jsp
webapp/checkoutbuynow.jsp

🎈 [FEAT] 결제 확인서 내 정보 불러오기

---

resources/mapper/CartMapper.xml
src/app/impl/cart/CartDaoImpl.java
src/app/impl/cart/CartServiceImpl.java
src/web/controller/MainServlet.java
src/web/controller/MemberServlet.java
test/cart/CartCountTest.java
webapp/checkout-result.jsp
webapp/checkout.jsp
webapp/checkoutbuynow.jsp
webapp/contact.jsp
webapp/main.jsp
webapp/mypage.jsp
webapp/shop-details.jsp
webapp/shop-grid.jsp
webapp/shoping-cart.jsp
webapp/signin.jsp
webapp/signup.jsp

🎈 [FEAT] 장바구니 페이지

---

resources/mapper/MemberMapper.xml
src/app/impl/member/MemberDaoImpl.java
src/app/impl/member/MemberServiceImpl.java
src/web/controller/MemberServlet.java
webapp/index.jsp
webapp/member-info-login.jsp
webapp/member-info.jsp
webapp/signin.jsp
webapp/signup.jsp

😀[FEAT]: 회원정보 조회/수정 완료

---

resources/mapper/OrderMapper.xml
resources/mapper/ProductMapper.xml
src/app/dto/entity/Order.java
src/app/dto/entity/Product.java
src/app/impl/order/OrderServiceImpl.java
src/app/impl/orderdetail/OrderDetailServiceImpl.java
src/app/impl/product/ProductDaoImpl.java
src/app/impl/product/ProductServiceImpl.java
src/web/controller/MainServlet.java
webapp/checkout-result.jsp
webapp/checkout.jsp
webapp/checkoutbuynow.jsp

💛 [FEAT] 장바구니에서 주문

---

src/web/controller/MainServlet.java
webapp/index.jsp
webapp/mypage.jsp
webapp/shoping-cart.jsp

🎈 [FEAT] 장바구니 구매 후 장바구니에서 삭제

---

src/web/controller/MainServlet.java
webapp/checkout-result.jsp
webapp/checkout.jsp
webapp/checkoutbuynow.jsp

💛 [FEAT] 바로주문과 장바구니에서 주문 통합

---

src/app/impl/cart/CartServiceImpl.java
src/web/controller/ProductDetailServlet.java
src/web/controller/RestController.java
src/web/controller/SearchServlet.java
webapp/shop-details.jsp

- [ x ] Feature 병합
넣기 전.
로그인 안되어있을시.
들어갔음.
바로구매 연동 확인
TODO: 로그인 안되어있는데 alert 뜨고, 모달이 안열려야하는데 모달 열리는거 확인. 바로 수정하겠음.
- [ x ] 정상 작동

✈ [FEAT] 상품상세 -> 장바구니/ 바로구매로 연동

---

resources/mapper/PointMapper.xml
resources/mybatis.xml
src/app/dto/entity/Point.java
src/app/enums/PointStateEnum.java
src/app/impl/point/PointDaoImpl.java
src/app/impl/point/PointServiceImpl.java
src/web/controller/MainServlet.java
src/web/controller/MemberServlet.java

🎈 [FEAT] 포인트 적립

---

webapp/index.jsp
webapp/main.jsp

모든 페이지에서 보이던 이벤트 팝업 메인에서만 보이도록 수정

💛 [BUG] 모든 페이지에서 보이던 이벤트 팝업 메인에서만 보이도록 수정

---

webapp/index.jsp

💛 [FEAT] 채널톡 추가

---

src/web/controller/MemberServlet.java
webapp/categorypage.jsp
webapp/main.jsp
webapp/member-info-login.jsp
webapp/member-info.jsp
webapp/search.jsp

🎈 [FIX] 로고 메인 충돌 & 로그아웃 시 추천 도서 리스트 오류 해결

---

webapp/index.jsp

💛 [FEAT] 실종되었던 favicon 추가

---

webapp/checkout-result.jsp
webapp/checkoutbuynow.jsp
webapp/index.jsp
webapp/main.jsp
webapp/signup.jsp

💛 [FEAT] 주문 완료시 이메일로 주문내역 발송

---

webapp/category.jsp
webapp/checkout-result.jsp
webapp/checkout.jsp
webapp/checkoutbuynow.jsp
webapp/contact.jsp
webapp/main.jsp
webapp/member-info-login.jsp
webapp/member-info.jsp
webapp/mypage.jsp
webapp/search.jsp
webapp/shop-details.jsp
webapp/shoping-cart.jsp
webapp/signin.jsp
webapp/signup.jsp

🍺 [FIX] : Shop 리다이렉트 url 값 수정

---

webapp/main.jsp

🎈[FIX] 오류 수정

---

webapp/index.jsp

🎈 [REFACTOR] 스크롤바 CSS 수정

---

test/review/ReviewsSelect.java
webapp/shop-details.jsp

- [ x] Feature 병합
- [ x] 정상 작동

✈ [FIX] 장바구니 들어가는 버그

---

webapp/shop-details.jsp

✈ [CHORE] 댓글 없을시 레이아웃 분기처리, 총 금액 , 표시

---

src/web/controller/MainServlet.java
webapp/checkout-result.jsp
webapp/checkout.jsp
webapp/checkoutbuynow.jsp
webapp/index.jsp
webapp/popup.jsp
webapp/shop-details.jsp

🎈 [FIX] 오류 수정

---

resources/mapper/OrderMapper.xml
src/web/controller/MainServlet.java
src/web/controller/ProductDetailServlet.java
webapp/404.jsp
webapp/category.jsp
webapp/checkout-result.jsp
webapp/checkout.jsp
webapp/checkoutbuynow.jsp
webapp/contact.jsp
webapp/main.jsp
webapp/member-info-login.jsp
webapp/member-info.jsp
webapp/mypage.jsp
webapp/search.jsp
webapp/shop-details.jsp
webapp/shoping-cart.jsp
webapp/signin.jsp
webapp/signup.jsp

🎈 [FIX] 메뉴 버튼 리다이렉션 설정

---

webapp/signin.jsp

- [ x] Feature 병합
더 좁히면 이상해서 이렇게 했어요.
- [ x] 정상 작동

✈ [DESIGN] 로그인 레이아웃 수정

---

src/app/impl/order/OrderServiceImpl.java
src/app/impl/orderdetail/OrderDetailServiceImpl.java
webapp/404.jsp
webapp/category.jsp
webapp/checkout-result.jsp
webapp/checkout.jsp
webapp/checkoutbuynow.jsp
webapp/contact.jsp
webapp/main.jsp
webapp/member-info-login.jsp
webapp/member-info.jsp
webapp/mypage.jsp
webapp/search.jsp
webapp/shop-details.jsp
webapp/shoping-cart.jsp
webapp/signin.jsp
webapp/signup.jsp

💛 [FEAT] Header에서 햄버거바 삭제

---

src/web/controller/MainServlet.java
webapp/checkout.jsp
webapp/checkoutbuynow.jsp
webapp/main.jsp

🎈 [FIX] 10자 이하 책 정보 주문 오류 해결

---

resources/mapper/CartMapper.xml
webapp/category.jsp
webapp/main.jsp
webapp/search.jsp

🎈 [FIX] 장바구니 담기 오류 해결 & UI 변경

---

webapp/index.jsp
webapp/shop-details.jsp

💛 [FEAT] 카카오 공유하기 기능 추가

---

webapp/shop-details.jsp

🎈 [FEAT] 카카오톡 공유하기 & 링크 주소 복사 UI 설정 및 기능 추가

---

resources/mapper/OrderDetailMapper.xml
resources/mapper/ReviewMapper.xml
resources/mybatis.xml
src/app/dto/entity/Order.java
src/app/dto/entity/Review.java
src/app/dto/response/OrderDetailResponse.java
src/app/impl/orderdetail/OrderDetailDaoImpl.java
src/app/impl/orderdetail/OrderDetailServiceImpl.java
src/app/impl/review/ReviewDaoImpl.java
src/app/impl/review/ReviewServiceImpl.java
src/web/controller/MainServlet.java
src/web/controller/ReviewServlet.java
test/review/ReviewSelectByProductAndMember.java
webapp/mypage.jsp

😀[FEAT]: Review에 orderdetail_sequence 추가

---

webapp/index.jsp

💛 [FEAT] META TAG 추가

---

resources/mapper/CategoryMapper.xml
src/app/impl/category/CategoryDaoImpl.java
src/app/impl/search/SearchServiceImpl.java
src/web/controller/SearchServlet.java
webapp/index.jsp
webapp/search.jsp
webapp/shop-details.jsp

- [x ] Feature 병합
- [ x] 정상 작동

✈ [FEAT] 검색 페이지네이션, 품절상품 프론트 예외처리, 검색 인코딩

---

resources/mapper/MemberMapper.xml
src/app/impl/member/MemberDaoImpl.java
src/app/impl/member/MemberServiceImpl.java
src/web/controller/RestController.java
src/web/controller/ReviewServlet.java
test/review/ReviewUpdatePoint.java
test/review/ReviewsSelect.java
webapp/member-info-login.jsp
webapp/mypage.jsp

[REFACTOR]: 마이페이지 리팩토링

---

resources/mapper/MemberMapper.xml
src/web/controller/MainServlet.java
src/web/controller/MemberServlet.java
src/web/controller/ReviewServlet.java
test/member/MemberInsert.java
test/member/MemberSelect.java
test/review/ReviewSelectByProductAndMember.java
test/review/ReviewsSelect.java
webapp/member-info.jsp
webapp/mypage.jsp

😀[REFACTOR]: console.log, syso, 주석 삭제

---

webapp/mypage.jsp

- [] Feature 병합
- [] 버그 수정(아래에 상세 기입)

😀[REFACTOR]: 정윤님 코드를 베이스로 랙팩토링+ 리뷰 별점 빨강->노랑으로 변경

---

resources/mapper/ProductMapper.xml
src/app/impl/product/ProductDaoImpl.java
src/app/impl/product/ProductServiceImpl.java
src/web/controller/MainServlet.java
src/web/controller/RestController.java
webapp/mypage.jsp

🎈 [FEAT] 주문 확정/취소/환불 시 주문 상태 및 상품 상태 변경 & 주문 확정 시 포인트 적립

---

webapp/category.jsp

🍺 [FIX] 한글 번역 및 필요없는 코드 삭제

---

src/web/controller/ReviewServlet.java
webapp/mypage.jsp

주문취소는 회색 배경으로 변환
- [] Feature 병합

😀[REFACTOR]: mypage) '나의 포인트' 최신화, 리뷰 작성시 포인트 적립 추가, 배송 상태 영문에서 한글로 수정,

---

webapp/mypage.jsp

😀[REFACTOR]: mypage "내역이 없습니다" 문구 추가

---

webapp/member-info.jsp

😀[REFACTOR]: 회원정보 취소시 mypage로 이동

---

src/app/impl/product/ProductServiceImpl.java
webapp/index.jsp
webapp/mypage.jsp
webapp/shoping-cart.jsp

🎈 [FIX] 주문 취소 시 재고 수정 & 푸터 로고 태그 변경

---

src/app/impl/search/SearchServiceImpl.java
src/web/controller/ProductDetailServlet.java
webapp/search.jsp
webapp/shop-details.jsp

✈ [Design] Search - 재고없는 레이아웃 변경, serach service refactoring

---

src/web/controller/MainServlet.java
src/web/controller/RestController.java
webapp/checkoutbuynow.jsp

- 카카오페이 연동중
- 승인 이후 결제 내역 화면으로 이동 오류
- 장바구니에서 결제 시 카카오페이 연동(승인 이후 결제 내역 화면으로 이동)

🎈 [FEAT] 카카오페이 연동

---

src/web/controller/MemberServlet.java

😀[REFACTOR]: 존재하지 않는 아이디로 로그인시 메시지 보여주기

---

resources/mapper/ProductMapper.xml
src/web/dispatcher/DispatcherServlet.java

💛 [FIX] 제품 상세 조회시 mapper 대소문자 구분 오류 수정

💛 [FIX] 제품 상세 조회시 mapper 대소문자 구분 오류 수정

---

resources/mapper/CartMapper.xml
resources/mapper/OrderDetailMapper.xml
resources/mapper/OrderMapper.xml
resources/mapper/PointMapper.xml
resources/mapper/ProductMapper.xml

[참고](https://zzang9ha.tistory.com/328)

💛 [FIX] aws sql 대소문자 구분으로 인해 mapper class 소문자로 변경

---

resources/mybatis.xml

💛 [FEAT] 불필요한 custMapper 삭제

---

webapp/checkout-result.jsp
webapp/contact.jsp
webapp/search.jsp
webapp/shop-details.jsp

💛 [FEAT] contact, shop-detail header 설정

---

src/app/impl/search/SearchServiceImpl.java
webapp/search.jsp

✈ [FIX] 컴퓨터공학 카테고리 개수 안나오는 버그, 상품상세 이동시 링크 주소 localhost -> 127.0.0.1

---

webapp/search.jsp

✈ [FIX] search에서 link 클릭시 보내주는 url 변경

---

webapp/signup.jsp

💛 [HOTFIX] signup 엔터누르자마자 회원가입 성공 버그 해결

---

resources/mapper/MemberMapper.xml
src/app/impl/member/MemberDaoImpl.java
src/app/impl/member/MemberServiceImpl.java
src/web/controller/MainServlet.java
webapp/checkout.jsp
webapp/checkoutbuynow.jsp

🎈 [HOTFIX] 주문 확정 후 사용자 포인트 적립

---

webapp/css/style.css

💛 [FEAT] cart icon 모바일 디자인 적용

---

src/web/controller/MainServlet.java
webapp/mypage.jsp
webapp/shop-details.jsp
webapp/shoping-cart.jsp

🎈 [HOTFIX] 품절된 장바구니 상품 주문 오류 해결 & URL 복사 오류 해결

---

webapp/mypage.jsp

😀[REFACTOR]: mypage 리팩토링

---

src/web/controller/MainServlet.java
webapp/checkoutbuynow.jsp
webapp/index.jsp

💛 [FEAT] 카카오페이 연동

---

src/web/controller/MainServlet.java
webapp/checkoutbuynow.jsp

💛 [HOTFIX] 카카오페이 총 금액 및 상품 못 받아 오는 버그 수정

---

webapp/checkout.jsp
webapp/checkoutbuynow.jsp
webapp/mypage.jsp

💛 [FEAT] 이전 장바구니 css 복원

---

webapp/shop-details.jsp

✈ [FIX] 상품디테일 평균별점 포매팅

---

webapp/checkout.jsp
webapp/checkoutbuynow.jsp

💛 [FEAT] 카카오 결제 성공시에만 결제 성공 페이지로 이동
